---
- hosts: webservers
  become: yes
  tasks:
  - name: Install the Linux Commands
    command: hostname -f
    register: myfirstresult

  - name: my results
    debug:
     msg: "{{myfirstresult}}"  