---
- hosts: appservers
  become: yes
  tasks:
  - name: Intsall mutiple Tasks
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - wget 
      - gnome-chess
      - rhythmbox
      - apache2
