---
- hosts: appservers
  become: yes
  tasks:
  - name: Install apache2
    apt:
      name: apache2
      state: present
    tags: myapache2

  - name: Install wget
    apt: 
      name: wget
      state: present
    tags: mywget

  - name: Install git
    apt:
      name: git
      state: present
    tags: mygit  
