---
- hosts: webservers
  become: yes
  tasks:
  - name: Install the Tree on Ubuntu
    apt:
      name: tree
      state: present
    when: ansible_os_family == "Debian"

  - name: start the tree service
    service:
      name: tree
      state: started  