---
- name: Download the tomcat installer
  get_url: 
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.8/bin/apache-tomcat-10.1.8.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.1.8.tar.gz
    force_basic_auth: yes 

- name: Create a Folder
  file:
     path: /opt/tomcat
     state: directory

- name: Extract the tomecat file
  command:
    cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-10.1.8.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/NOTICE